# Site settings
title: Gabriela Stafford
email: gstafford@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  News and updates from Gabriela Stafford, varsity athlete competing for the University of Toronto.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000.com" # CHANGE FOR LIVE
twitter_username: gstafford13
github_username:  gstafford

# Build settings
markdown: kramdown
